

spring:
  application:
    name: eureka

server:
  port: 9002
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
    register-with-eureka: true
    fetch-registry: true




