server:
  port: 9004
spring:
  application:
    name: lagou-gateway
  cloud:
    gateway:
      routers:
        - id: lagou-serivce-user
          uri: lb://lagou-serivce-user
          predicates:
            - Path=/user/**
        - id: lagou-service-code
          uri: lb://lagou-serivce-code
          predicates:
            - Path=/code/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka
    fetch-registry: true
    register-with-eureka: true

