server:
  port: 9003

spring:
  application:
    name: lagou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lixingyun0/lagou-config.git #配置git服务地址
      # 读取分支
      label: main


eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
